version: '2'

#networks:
#  my-network:
#    driver: bridge
services:
  openldap:
    image: bitnami/openldap:2
    ports:
      - '389:1389'
      - '636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_USERS=user01,user02
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=org
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_PASSWORDS=password1,password2